add_newline = true
command_timeout = 200
format = "[$hostname$directory$git_branch$git_metrics$git_status]($style)$character"

[hostname]
ssh_only = true
format = '[$hostname](bold green) '
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_metrics]
disabled = false
only_nonzero_diffs = true
added_style = "bold green"
deleted_style = "bold red"
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
